### ISSUE TITLE
Error when making new blog.

### ISSUE THREAD

**Issue by EntranceJew** [iandunn/WordPress-Plugin-Skeleton#5]
The following lines of code produce the following error when a new blog is created when wpmu is enabled / on a multisite:
`Fatal error: Using $this when not in object context` and the trace brings up these important lines of code:
https://github.com/iandunn/WordPress-Plugin-Skeleton/blob/master/classes/wordpress-plugin-skeleton.php#L167
https://github.com/iandunn/WordPress-Plugin-Skeleton/blob/master/classes/wordpress-plugin-skeleton.php#L129

If you change line 167 to be:
```php
add_action( 'wpmu_new_blog',         array( $this, 'activate_new_site' ) );
```

Then everything works out perfectly. I don't have the time on my hand to write a full blown unit test for this so the least I could do is document the issue. Thanks for the great starting point for a plugin.

**Comment by iandunn** [comment]
Thanks for the report :)
